[package]
name = "dnote-tui"
version = "0.1.0"
edition = "2021"
default-run = "dnote-tui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.22.0" }
